### ISSUE TITLE
Question: can this be used with cargo-lambda, or are they incompatible?

### ISSUE THREAD

**Issue by afparsons** [hanabu/lambda-web#15]
I am **_extremely_** new to both the Rust ecosystem and to AWS Lambda; please excuse my naivety.

In my two hours of research on how I would use Rust on AWS Lambda, I felt repeatedly steered toward [`cargo-lambda`](https://www.cargo-lambda.info/). 

Should this crate be used _in addition to_ or _instead of_ [`cargo-lambda`](https://www.cargo-lambda.info/)?

I'm tripped up with the handler function; it seems like [`cargo-lambda`](https://www.cargo-lambda.info/) automatically sets up its idea of a handler function and [`lambda-web`](https://github.com/hanabu/lambda-web) also provides a handler function (depending on the web framework being used). Does that mean that these two crates are incompatible?

---
This looks like a cool project, so I just wanted to extend my congratulations, even if I don't quite understand it all yet :sweat_smile: 

---

EDIT: ah, wait, I might have figured it out; I'll update and potentially close this question soon.

**Comment by tgandrews** [comment]
Did you resolve this?

**Comment by memark** [comment]
They can definitely be used to together without much trouble. Suggest closing this issue.

**Comment by andrew-parsons-janus** [comment]
I haven't looked at this in any detail since I posted. Closing.

**Comment by afparsons** [comment]
Thanks for your thoughts! I haven't looked at this in almost a year. Closing.
