### ISSUE TITLE
Support API Gateway REST API

### ISSUE THREAD

**Issue by sedrik** [hanabu/lambda-web#2]
At work we use the REST API Gateway and it would be awesome to be able to use rocket lambdas on that.

What would be needed to support the REST Gateway? With some mentoring I could take a look at implementing support for it.

**Comment by hanabu** [comment]
@sedrik ,
Sorry for delayed response. I published 0.1.7 which supports REST API.

**Comment by sedrik** [comment]
That is amazing.

I will see if I can get some time to play around and test it soon.

Thanks for the help, I will close this and open any new issues if I run into something.
